import type { Metadata } from "next";
import { Cabin } from "next/font/google";
import localFont from 'next/font/local';
import 'prismjs';
import 'katex';

import "./globals.css";

import "react-notion-x/src/styles.css";
import "prismjs/themes/prism-tomorrow.css";
import "katex/dist/katex.min.css";

import { Provider as ThemeProvider } from "@/state/theme";
import { Provider as QueryProvider } from "@/state/query";

const cabin = Cabin({
  subsets: ['latin'],
  variable: '--font-cabin',
});

const helloImperfect = localFont({
  src: [
    {
      path: 'fonts/hello-imperfect.woff2',
      weight: '400',
      style: 'normal',
    },  
  ],
  variable: '--font-hello-imperfect',
});

const forest = localFont({
  src: [
    {
      path : 'fonts/forrest-light.woff2',
      weight : '300',
      style : 'normal',
    },
    {
      path : 'fonts/forrest-lightitalic.woff2',
      weight : '300',
      style : 'italic',
    },
    {
      path : 'fonts/forrest-regular.woff2',
      weight : '400',
      style : 'normal',
    },
    {
      path : 'fonts/forrest-regularitalic.woff2',
      weight : '400',
      style : 'italic',
    },
    {
      path : 'fonts/forrest-medium.woff2',
      weight : '500',
      style : 'normal',
    },
    {
      path : 'fonts/forrest-mediumitalic.woff2',
      weight : '500',
      style : 'italic',
    },
    {
      path : 'fonts/forrest-bold.woff2',
      weight : '600',
      style : 'normal',
    },
    {
      path : 'fonts/forrest-bolditalic.woff2',
      weight : '600',
      style : 'italic',
    },
    {
      path : 'fonts/forrest-extrabold.woff2',
      weight : '700',
      style : 'normal',
    },
    {
      path : 'fonts/forrest-extrabolditalic.woff2',
      weight : '700',
      style : 'italic',
    },
    {
      path : 'fonts/forrest-heavy.woff2',
      weight : '800',
      style : 'normal',
    },
    {
      path : 'fonts/forrest-heavyitalic.woff2',
      weight : '800',
      style : 'italic',
    },
    
  ],
  variable: '--font-forest',
});

const fantasqueSans = localFont({
  src: [
    {
      path: 'fonts/fantasquesans-regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: 'fonts/fantasquesans-bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: 'fonts/fantasquesans-bolditalic.woff2',
      weight: '700',
      style: 'italic',
    },
    {
      path: 'fonts/fantasquesans-italic.woff2',
      weight: '400',
      style: 'italic',
    },
  ],
  variable: '--font-fantasque',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <QueryProvider>
        <body
          className={`${forest.variable} ${fantasqueSans.variable} ${cabin.variable} ${helloImperfect.variable} antialiased`}
        >
          <ThemeProvider>
            {children}
          </ThemeProvider>
        </body>
      </QueryProvider>
    </html>
  );
}
